package:
  name: libcdio
  version: 2.2.0
  epoch: 0
  description: GNU Compact Disc Input and Control Library
  copyright:
    - license: GPL-3.0-or-later
environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - glibc-iconv
      - gnu-libiconv-dev
      - libtool
      - ncurses-dev
      - pkgconf
      - texinfo
      - wolfi-base
pipeline:
  - uses: git-checkout
    with:
      repository: https://git.savannah.gnu.org/git/libcdio.git
      tag: ${{package.version}}
      expected-commit: 3922b045fa3dfa7c8e062641ac619a344e23c0a9
  - runs: |
      # Remove libtool directory if it exists (conflicts with libtool script generation)
      [ -d libtool ] && rm -rf libtool || true
      autoreconf -fi
      # Ensure dependency tracking directories exist
      find . -name Makefile.in -exec dirname {} \; | xargs -I {} mkdir -p {}/.deps
  - runs: |
      export CFLAGS="-I/usr/include/gnu-libiconv $CFLAGS"
      export LDFLAGS="-L/usr/lib $LDFLAGS"
      ./configure \
        --prefix=/usr \
        --disable-static \
        --disable-vcd-info \
        --disable-cpp-progs \
        --disable-cxx \
        --enable-shared \
        --disable-dependency-tracking
  - runs: |
      # Skip documentation build by removing doc from SUBDIRS
      sed -i 's/\(SUBDIRS.*\) doc/\1/' Makefile
      # Skip example directory (has libtool dependency issues in 2.2.0)
      sed -i 's/\(SUBDIRS.*\) example/\1/' Makefile
      # Skip C++ bindings (--disable-cxx doesn't fully work in 2.2.0)
      sed -i 's/\(SUBDIRS.*\) cdio++/\1/' lib/Makefile
      sed -i 's/\(SUBDIRS.*\) cdio++/\1/' include/Makefile
      # Create dummy man pages that src/ expects
      touch src/cd-drive.1 src/cd-info.1 src/cd-read.1 src/iso-info.1 src/iso-read.1
  - uses: autoconf/make
  - uses: autoconf/make-install
  - name: 'Clean up documentation'
    runs: |
      rm -rf ${{targets.destdir}}/usr/share/info
      rm -rf ${{targets.destdir}}/usr/share/doc
  - uses: strip
subpackages:
  - name: libcdio-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - libcdio
    description: libcdio development files
    test:
      pipeline:
        - uses: test/pkgconf
  - name: libcdio-doc
    pipeline:
      - uses: split/manpages
    description: libcdio documentation
update:
  enabled: true
  release-monitor:
    identifier: 1573
test:
  pipeline:
    - name: Verify library exists
      runs: |
        test -f /usr/lib/libcdio.so
    - name: Test cd-info binary
      runs: |
        cd-info --version
    - uses: test/pkgconf
