package:
  name: mpv
  version: 0.40.0
  epoch: 0
  description: Free, open source, and cross-platform media player
  copyright:
    - license: GPL-2.0-or-later AND LGPL-2.1-or-later
  dependencies:
    runtime:
      - libmpv2=${{package.full-version}}

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - ffmpeg-dev
      - lcms2-dev
      - libarchive-dev
      - libass-dev
      - libbluray-dev
      - libcdio-paranoia-dev
      - libdvdnav-dev
      - libdvdread-dev
      - libjpeg-turbo-dev
      - libplacebo-dev
      - libva-dev
      - libvdpau-dev
      - libxkbcommon-dev
      - libxpresent-dev
      - libxrandr-dev
      - libxscrnsaver-dev
      - libxv-dev
      - lua5.2-dev
      - meson
      - mujs-dev
      - openssl-dev
      - pipewire-dev
      - pulseaudio-dev
      - python3
      - rubberband-dev
      - shaderc-dev
      - uchardet-dev
      - vapoursynth-dev
      - vulkan-headers
      - vulkan-loader-dev
      - wayland-dev
      - wayland-protocols
      - wolfi-base
      - zimg-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/mpv-player/mpv
      tag: v${{package.version}}
      expected-commit: 8a7fa3b0fa42f3933de988ea0dc7f15b66e25af9

  - uses: meson/configure
    with:
      opts: |
        -Dlibmpv=true \
        -Dlua=lua5.2 \
        -Dcplayer=true \
        -Dbuild-date=false \
        -Dcdda=enabled \
        -Ddvbin=enabled \
        -Ddvdnav=enabled \
        -Dlibarchive=enabled \
        -Dshaderc=enabled

  - uses: meson/compile

  - uses: meson/install

  - uses: strip

subpackages:
  - name: libmpv2
    description: mpv media player library
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/libmpv.so.2* "${{targets.subpkgdir}}"/usr/lib/
    test:
      pipeline:
        - uses: test/tw/ldd-check

  - name: mpv-dev
    description: mpv development files
    dependencies:
      runtime:
        - libmpv2
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/pkgconf
          with:
            expected-name: mpv
        - uses: test/tw/ldd-check

  - name: mpv-doc
    description: mpv documentation
    pipeline:
      - uses: split/manpages
    test:
      pipeline:
        - uses: test/docs

  - name: mpv-bash-completion
    description: Bash completion for mpv
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/bash-completion/completions
          mv "${{targets.destdir}}"/usr/share/bash-completion/completions/mpv \
            "${{targets.subpkgdir}}"/usr/share/bash-completion/completions/

  - name: mpv-zsh-completion
    description: Zsh completion for mpv
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/zsh/site-functions
          mv "${{targets.destdir}}"/usr/share/zsh/site-functions/_mpv \
            "${{targets.subpkgdir}}"/usr/share/zsh/site-functions/

update:
  enabled: true
  github:
    identifier: mpv-player/mpv
    strip-prefix: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - ffmpeg
  pipeline:
    - name: Test mpv binary exists and runs
      runs: |
        mpv --version
        mpv --help

    - name: Test library linkage
      runs: |
        ldd /usr/bin/mpv | grep libmpv

    - name: Verify mpv can process test video
      runs: |
        # Create a test video using ffmpeg
        ffmpeg -f lavfi -i testsrc=duration=1:size=320x240:rate=1 -pix_fmt yuv420p test.mp4

        # Test mpv can analyze the file (without playing)
        mpv --no-config --vo=null --ao=null --frames=1 test.mp4

    - uses: test/no-docs
