package:
  name: mujs
  version: 1.3.7
  epoch: 0
  description: Lightweight JavaScript interpreter
  copyright:
    - license: ISC

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - curl
      - python3
      - readline-dev
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/ArtifexSoftware/mujs.git
      tag: ${{package.version}}
      expected-commit: 05cd646bad083ed45e9e1c9846ea671d461ced30

  - uses: autoconf/make
    with:
      opts: |
        prefix=/usr \
        CFLAGS="-fPIC" \
        release

  - runs: |
      make install DESTDIR="${{targets.destdir}}" prefix=/usr

  - uses: strip

subpackages:
  - name: mujs-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - mujs
    description: mujs development files
    test:
      pipeline:
        - uses: test/pkgconf

update:
  enabled: true
  release-monitor:
    identifier: 269367

test:
  pipeline:
    - name: Test mujs binary
      runs: |
        mujs -v
    - name: Verify library exists
      runs: |
        test -f /usr/lib/libmujs.so.1
    - uses: test/pkgconf
