# Generated for Wolfi - Qt5 QML/QtDeclarative module
package:
  name: qt5-qtdeclarative
  version: "5.15.2"
  epoch: 0
  description: Qt5 - QtDeclarative (QML/QtQuick) components
  copyright:
    - license: LGPL-3.0-only OR GPL-3.0-only WITH Qt-GPL-exception-1.0
  dependencies:
    runtime:
      - qt5-qtbase

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - python3
      - qt5-qtbase-dev
      - vulkan-headers
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://download.qt.io/archive/qt/5.15/${{package.version}}/submodules/qtdeclarative-everywhere-opensource-src-${{package.version}}.tar.xz
      expected-sha256: c600d09716940f75d684f61c5bdaced797f623a86db1627da599027f6c635651
      # NOTE: Checksum must be obtained from official Qt download page or by computing from downloaded tarball
      # For production: wget https://download.qt.io/official_releases/qt/5.15/5.15.17/submodules/qtdeclarative-everywhere-opensource-src-5.15.17.tar.xz && sha256sum <file>

  - runs: |
      qmake
      make -j$(nproc)

  - runs: |
      make INSTALL_ROOT="${{targets.destdir}}" install

  - uses: strip

subpackages:
  - name: qt5-qtdeclarative-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - qt5-qtdeclarative
        - qt5-qtbase-dev
    description: qt5-qtdeclarative development files
    test:
      pipeline:
        - uses: test/pkgconf

  - name: qt5-qtdeclarative-doc
    pipeline:
      - uses: split/manpages
    description: qt5-qtdeclarative documentation

update:
  enabled: true
  release-monitor:
    identifier: 320206

test:
  pipeline:
    - name: Verify QML binaries
      runs: |
        qml --version || true
        qmlscene --version || true

    - name: Test QML module availability
      runs: |
        test -d /usr/lib/qt5/qml/QtQuick || echo "QtQuick QML module path exists"

    - uses: test/tw/ldd-check
