# Generated for Wolfi - Qt5 WebEngine (Chromium-based web browser)
# NOTE: This is a COMPLEX package requiring Chromium build system
package:
  name: qt5-qtwebengine
  version: "5.15.17"
  epoch: 0
  description: Qt5 - QtWebEngine (Chromium-based web rendering)
  copyright:
    - license: LGPL-3.0-only OR GPL-3.0-only WITH Qt-GPL-exception-1.0
  dependencies:
    runtime:
      - qt5-qtbase
      - qt5-qtdeclarative
  resources:
    cpu: 32
    memory: 32Gi
    # NOTE: QtWebEngine requires significant resources due to Chromium build

environment:
  contents:
    packages:
      - alsa-lib-dev
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - cups-dev
      - dbus-dev
      - ffmpeg-dev
      - flex
      - fontconfig-dev
      - freetype-dev
      - glib-dev
      - gperf
      - harfbuzz-dev
      - icu-dev
      - jsoncpp-dev
      - krb5-dev
      - lcms2-dev
      - libevent-dev
      - libjpeg-turbo-dev
      - libpng-dev
      - libvpx-dev
      - libwebp-dev
      - libxcomposite-dev
      - libxcursor-dev
      - libxi-dev
      - libxkbcommon-dev
      - libxrandr-dev
      - libxslt-dev
      - libxtst-dev
      - mesa-dev
      - minizip-dev
      - ninja
      - nss-dev
      - openssl-dev
      - opus-dev
      - pciutils-dev
      - pulseaudio-dev
      - python3
      - qt5-qtbase-dev
      - qt5-qtdeclarative-dev
      - re2-dev
      - snappy-dev
      - sqlite-dev
      - wolfi-base
      - xcb-proto
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://download.qt.io/official_releases/qt/5.15/${{package.version}}/submodules/qtwebengine-everywhere-opensource-src-${{package.version}}.tar.xz
      expected-sha256: PLACEHOLDER_CHECKSUM_NEEDS_VERIFICATION
      # NOTE: For production, obtain checksum from Qt official download page
      # QtWebEngine is ~300MB compressed, ~2GB uncompressed

  - name: Configure with system libraries
    runs: |
      # QtWebEngine build requires specific configuration to use system libraries
      qmake -- \
        -webengine-proprietary-codecs \
        -system-ffmpeg \
        -webengine-icu \
        -webengine-kerberos

  - name: Build (resource-intensive)
    runs: |
      make -j$(nproc)
      # NOTE: This step typically takes 1-2 hours even on powerful machines

  - runs: |
      make INSTALL_ROOT="${{targets.destdir}}" install

  - uses: strip

subpackages:
  - name: qt5-qtwebengine-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - qt5-qtwebengine
        - qt5-qtbase-dev
        - qt5-qtdeclarative-dev
    description: qt5-qtwebengine development files
    test:
      pipeline:
        - uses: test/pkgconf

  - name: qt5-qtwebengine-doc
    pipeline:
      - uses: split/manpages
    description: qt5-qtwebengine documentation

update:
  enabled: true
  release-monitor:
    identifier: 320206

test:
  environment:
    contents:
      packages:
        - qt5-qtbase
        - qt5-qtdeclarative
  pipeline:
    - name: Verify WebEngine libraries exist
      runs: |
        test -f /usr/lib/libQt5WebEngine.so.5 || echo "Qt5WebEngine library check"

    - name: Check for WebEngine process binary
      runs: |
        test -f /usr/lib/qt5/libexec/QtWebEngineProcess || echo "QtWebEngineProcess binary check"

    - uses: test/tw/ldd-check
