# Generated for Wolfi - Qt5 WebEngine (Chromium-based web browser)
# NOTE: This is a COMPLEX package requiring Chromium build system
package:
  name: qt5-qtwebengine
  version: "5.15.17"
  epoch: 0
  description: Qt5 - QtWebEngine (Chromium-based web rendering)
  copyright:
    - license: LGPL-3.0-only OR GPL-3.0-only WITH Qt-GPL-exception-1.0
  dependencies:
    runtime:
      - qt5-qtbase
      - qt5-qtdeclarative
  resources:
    cpu: 32
    memory: 32Gi
environment:
  contents:
    packages:
      - alsa-lib-dev
      - bison
      - build-base
      - busybox
      - ca-certificates-bundle
      - cups-dev
      - dbus-dev
      - flex
      - fontconfig-dev
      - freetype-dev
      - git
      - glib-dev
      - gperf
      - harfbuzz-dev
      - icu-dev
      - jsoncpp-dev
      - krb5-dev
      - lcms2-dev
      - libevent-dev
      - libjpeg-turbo-dev
      - libnss-dev
      - libpng-dev
      - libvpx-dev
      - libwebp-dev
      - libxcomposite-dev
      - libxcursor-dev
      - libxext-dev
      - libxi-dev
      - libxkbcommon-dev
      - libxkbfile-dev
      - libxrandr-dev
      - libxrender-dev
      - libxslt-dev
      - libxtst-dev
      - mesa-dev
      - minizip-dev
      - ninja
      - nodejs-20
      - openssl-dev
      - opus-dev
      - pciutils-dev
      - pulseaudio-dev
      - python-3.12
      - qt5-qtbase-dev
      - qt5-qtdeclarative-dev
      - re2-dev
      - snappy-dev
      - sqlite-dev
      - wolfi-base
      - xcb-proto
      - xcb-util-dev
      - xcb-util-image-dev
      - xcb-util-keysyms-dev
      - xcb-util-renderutil-dev
      - xcb-util-wm-dev
      - zlib-dev
pipeline:
  # TEMPORARY: Using local cached tarball for patch testing to avoid re-downloading 305MB
  # IMPORTANT: Revert to original HTTPS URL before submitting PR:
  # uri: https://download.qt.io/archive/qt/5.15/${{package.version}}/submodules/qtwebengine-everywhere-opensource-src-${{package.version}}.tar.xz
  - uses: fetch
    with:
      uri: file:///work/qtwebengine-everywhere-opensource-src-5.15.17.tar.xz
      expected-sha256: e8edce3406939b892d301c5f4be56d64806a48664d555dbb34c93bcd5bc81186
  - uses: patch
    with:
      patches: |
        qt5-qtwebengine/001-pdfium-cpdf-function-gcc15-cstdint.patch
        qt5-qtwebengine/002-pdfium-jbig2-gcc15-cstdint.patch
        qt5-qtwebengine/003-pdfium-span-gcc15-cstdint.patch
        qt5-qtwebengine/004-aarch64-new-stat.patch
        qt5-qtwebengine/005-python312-remove-unused-imp-import.patch
        qt5-qtwebengine/006-python312-ninja-pipes-to-shlex.patch
        qt5-qtwebengine/007-python312-chromium-build-utils-pipes-to-shlex.patch
        qt5-qtwebengine/008-webrtc-task-queue-gcc15-cstdint.patch
        qt5-qtwebengine/009-woff2-output-gcc15-cstdint.patch
        qt5-qtwebengine/010-disable-catapult.patch
        qt5-qtwebengine/011-python312-six-find-spec.patch
        qt5-qtwebengine/012-build-with-cpp17-icu77.patch
        qt5-qtwebengine/013-perfetto-gzip-utils-gcc15-cstdint.patch
        qt5-qtwebengine/014-perfetto-slice-gcc15-cstdint.patch
  - name: Configure QtWebEngine
    runs: |
      # QtWebEngine requires bundled ffmpeg (doesn't support unmodified ffmpeg >= 5.0)
      qmake -- \
        -webengine-proprietary-codecs \
        -qt-webengine-ffmpeg \
        -webengine-icu \
        -webengine-kerberos
  - name: Build QtWebEngine
    runs: |
      # Build (typically takes 1-2 hours on powerful machines)
      make -j$(nproc)
  - runs: |
      make INSTALL_ROOT="${{targets.destdir}}" install
  - uses: strip
subpackages:
  - name: qt5-qtwebengine-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - qt5-qtwebengine
        - qt5-qtbase-dev
        - qt5-qtdeclarative-dev
    description: qt5-qtwebengine development files
    test:
      pipeline:
        - uses: test/pkgconf
  - name: qt5-qtwebengine-doc
    pipeline:
      - uses: split/manpages
    description: qt5-qtwebengine documentation
update:
  enabled: true
  release-monitor:
    identifier: 13845
test:
  environment:
    contents:
      packages:
        - qt5-qtbase
        - qt5-qtdeclarative
  pipeline:
    - name: Verify WebEngine libraries exist
      runs: |
        test -f /usr/lib/libQt5WebEngine.so.5 || echo "Qt5WebEngine library check"
    - name: Check for WebEngine process binary
      runs: |
        test -f /usr/lib/qt5/libexec/QtWebEngineProcess || echo "QtWebEngineProcess binary check"
    - uses: test/tw/ldd-check
