package:
  name: vapoursynth
  version: "72"
  epoch: 0
  description: Video processing framework with Python scripting
  copyright:
    - license: LGPL-2.1-or-later

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - libtool
      - pkgconf
      - python3-dev
      - wolfi-base
      - zimg-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/vapoursynth/vapoursynth.git
      tag: R${{package.version}}
      expected-commit: e46204429041e95a881b61eedddd46c08f9a307c

  - runs: |
      ./autogen.sh

  - uses: autoconf/configure
    with:
      opts: |
        --disable-static

  - uses: autoconf/make

  - uses: autoconf/make-install

  - uses: strip

subpackages:
  - name: vapoursynth-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - vapoursynth
    description: vapoursynth development files
    test:
      pipeline:
        - uses: test/pkgconf

update:
  enabled: true
  github:
    identifier: vapoursynth/vapoursynth
    strip-prefix: R
    use-tag: true
    tag-filter: R

test:
  pipeline:
    - name: Test vspipe binary
      runs: |
        vspipe --version
    - name: Verify library exists
      runs: |
        test -f /usr/lib/libvapoursynth.so
    - uses: test/pkgconf
